### ISSUE TITLE
AlpacaJapan株式会社より

### ISSUE THREAD

**Issue by gamella** [azu/open-job-letter#2]
* 会社情報
AlpacaJapan株式会社

* 会社/サービスURL
https://www.alpaca.ai/ja/

* 連絡先
北山のTwitter @gamella

* 連絡した理由

マーケット予測で世界で勝負しようとしている"B2B"の会社となります。

エンジニアは主に機械学習エンジニアが中心でしたが、これまで研究してきたマーケット予測の部分をコアに新しいプロダクトを開発するチームを作ろうと思っております。デザイナー・セールス・AIを設計する機械学習エンジニアと共同で、プロダクトを作り込めるフロントエンドエンジニアのテックリードを探しております。

現在、まさにシリーズAラウンドが完了し、拡大期の企業に該当すると考えております。

解決したい課題は、マーケット予測という金融における最難関の問題に対して、会社として
アタックできる体制をとり、組織としてこの問題に解決したいと考えております。
弊社設計のマーケット予測モデルを課題解決のために届けるために、最近デザイナーを採用しまして、
いよいよプロダクトをつくるフェーズにはいっております。

第一段のプロダクトはブルームバーグという世界最大の金融端末にリリースしました。
https://www.alpaca.ai/ja/alpacaforecast_app/
ブルームバーグにプロダクトをリリースすることのインパクトはなかなか金融領域の外の方はピンとこないかもしれませんが、スタートアップが達成するのは高い壁です。
そういう意味ではこのドメインではセールス含めて、とてもおもしろいチームになっていると思います。

* 業種（会社情報で分かる）
金融、マーケット予測、トレーディング

* 職種（会社情報で分かる）
フロントエンドエンジニア・アプリケーションエンジニア

* 勤務地（会社情報で分かることが殆ど）
弊社の神田オフィス

* 年収
800万円以上

**Comment by azu** [comment]
ご連絡ありがとうございます。

リアルタイムDBの[MarketStore](https://github.com/alpacahq/marketstore)が必要となった背景のお話やリアルタイムでどのように処理してるかのお話が興味深かったです。

- [Chainerを使って本気でマーケットの予測システムを作ったらこうなった](https://www.slideshare.net/gamella/chainer-101818811)
- [MarketStore、或いはアルパカの時系列データストレージと配信 - Alpaca技術ブログ](http://blog-jp.alpaca.ai/entry/2016/05/20/094831)

ファストデータについては[アプトポッド](https://www.aptpod.co.jp/index.html)さんの[技術](https://www.aptpod.co.jp/basetech/)の話でもみていましたが、ビックデータとの両立しようとするために様々な工夫が必要になりそうですね。
またそれをリアルタイムに扱えるユーザーインターフェースを作ろうとすると、クライアント側(ブラウザなど)のメモリなどの制約から、スムーズなUIを実現するためにはよくデザインされたものが必要になると思います。

それらの課題への挑戦は興味深いのですが、金融やマーケット予測などに強い興味を持てなかったため、申し訳ありませんがクローズさせていただきます。

**Comment by gamella** [comment]
ご検討ありがとうございました！
