### ISSUE TITLE
株式会社カブクです

### ISSUE THREAD

**Issue by kimamula** [azu/open-job-letter#4]
### 会社情報
株式会社カブク

従業員数: 約30名

所在地:
〒160-0022
東京都新宿区新宿5-17-17 渡菱ビル1F

（東証一部上場の双葉電子工業株式会社の連結子会社です）

#### コーポレートサイト
https://www.kabuku.co.jp/

JSer.infoで何度か取り上げていただいたことがありますが、Developers Blogをご覧いただくと、在籍しているエンジニアの雰囲気が伝わるかと思います。

https://www.kabuku.co.jp/developers

#### Connect
https://connect.kabuku.io/

特注品などを作りたい顧客企業を、グローバルな工場ネットワークとつなぐ（技術購買のアウトソーシング）サービスです

#### Rinkak
https://www.rinkak.com/

ユーザーが3Dデータをアップロードし、そこから3Dプリントプロダクトを試作したり、売ったり、買ったりできるサービスです

### 連絡した理由
以下のような点で、azuさんのご希望にマッチするのではないかと考え、ご連絡させていただきました。

- B2B
- 拡大期の企業
  - 昨年双葉電子工業株式会社の子会社となり、スタートアップの時期を終えて拡大しようとしているところです
- 課題
  - ものづくりの民主化
    - 大規模な製造設備を持たない個人、法人でも、簡単にものづくりをできるようにする「ものづくりの民主化」が会社としてのビジョンで、この課題をテクノロジーで解決することに取り組んでいます
    - 上記で紹介したConnectやRinkakはこのためのサービスです
  - 製造業のデジタル化
    - たとえば、以下のような用途に機械学習を適用しています
      - 3Dデータや2Dデータからの情報抽出モデルの構築
      - センサーデータの分析モデルの調査・研究・開発

### その他アピールポイント

エンジニアは上下関係がなくフラットで働きやすい雰囲気だと思います。
書籍の執筆やカンファレンス、勉強会での発表などのアウトプット活動も各人積極的に取り組んでいます。
会社として「自治あっての自由」というのを掲げていて、自由でありながら決してだらしなくはならないところもいいと思っています。

azuさんの求職記事をみた若手エンジニアが、azuさんに来て欲しいという思いが募ったあまりお席をフライングで用意してしまいました。
azuさんのお名前は3Dプリンタでプリントしたものですが、弊社では福利厚生で3Dプリンタが使い放題です。

![img_20181113_194342](https://user-images.githubusercontent.com/3130879/48411259-602c1080-e784-11e8-910a-70de97748bae.jpg)

興味を持っていただけましたら、ぜひお気軽にご返信ください。

**Comment by azu** [comment]
ご連絡ありがとうございます。

> JSer.infoで何度か取り上げていただいたことがありますが、

はい、以前から存じ上げています。
今回の求職活動中にも一度調べたことがあるのですが、どうしても株式会社カブクで自分が働いているイメージができなかったという感覚があります。
自分があまり物理的なものに興味をもつことが少ないので、製造業と少し距離があるからかもしれません。
申し訳ありませんがクローズさせていただきます。
