### ISSUE TITLE
グループ全体のフロントエンド力の底上げを一緒にしていただきたいです/メドピア株式会社

### ISSUE THREAD

**Issue by pipopotamasu** [azu/open-job-letter#5]
初めまして、[メドピア株式会社](https://medpeer.co.jp/)のフロントエンドエンジニアの村上大和([github](https://github.com/pipopotamasu))と申します。

弊社では社内のプロダクトの初期構築(技術選定含む)・フロントエンド環境の改善・エンジニアメンバの育成をできるリードフロントエンドエンジニアを探しております。
是非一度お話を伺えればと考えております。

詳細な情報については以下にまとめておりますので、もし興味を持てていただけたなら以下いずれかまでご連絡いただけたら幸いです。
(普段twitterをやっていないため、今回の連絡のやりとりのためにアカウント作りました)。

・ec0156hx@gmail.com
・https://twitter.com/pipopotamasu3
・https://www.facebook.com/yamato.murakami.3

## 連絡した背景
フロントエンドの観点から課題(プロダクトの目的や数値目標の達成)解決のために技術の提案、実装を行うことができる人を増やしたいため、リードフロントエンドエンジニアを募集しています。

事業の拡大及び資本提携で、社内では複数のプロダクト開発が同時に動いています。また今後も継続的にプロダクトの新規開発プロジェクトが動き始める想定です。
しかし現在社内にフロントエンドエンジニアが1名しか居らず、プロダクト全てに対して課題解決のために技術の提案、実装ができない状況です。

そのためリードフロントエンドエンジニアを採用し、「フロントエンドの観点から課題(プロダクトの目的や数値目標の達成)解決のために技術の提案、実装を行う」を達成できるようなフロントエンドエンジニアの組織作り・教育・技術のリードをしていただきたいと考えています(左記3つのうち2つ以上やっていただける方を希望しています)。

azu様の技術力の高さもちろん魅力的ですが、それ以上にレジュメに記載のあった「特定のチームや特定サービスではなく会社全体のフロントエンドを改善する」という文言を拝見させていただき、上記課題をazu様なら上手く解決していただけるのではと予感し連絡させていただいた次第です(個人的ですが「5分でわかるpower-assert」をみて、[power-assertを使わせていただきました](https://github.com/pipopotamasu/rails-vue/blob/master/package.json#L55))。

## 企業HP
https://medpeer.co.jp/

## テックブログ
https://tech.medpeer.co.jp/ 

## 業界
医療系、医師向けのポータルサイトをメインに運営している会社です。
子会社では、健康相談プラットフォームをBtoC及びBtoBに提供している会社や、健保組合向けに特定保健指導サービスを展開している会社もあります。
売上は100%近くtoBであげています。

## 企業のフェーズ
直近3年の売上が

9.7億円(2016実績) -> 15.5億円(2017実績) -> 22.4億円(2018予想)

と拡大フェーズにあります。
最近ではスギ薬局様と[業務資本提携](https://medpeer.co.jp/press/5087.html)を結び、さらに業務拡大をしております。

## デザイン
私自身デザイナーではないため、会社で取り組むデザインについて語ると認識齟齬が生まれる可能性があるため詳細に語ることを避けさせていただきます。
代わりと言っては何ですが、正社員として4名デザイナーが在籍しています。もし興味があるようでしたら、彼らとの面談を設定します。

## 課題
事業者としての課題を書かせていただきます。社内の課題については「連絡した背景」をお読みください。

メドピアグループとして4社あり、それぞれ解決しようとしている課題が違うため「グループ全体」の共通課題とそれに対するアプローチを書きます。

「集合知により医療を再発明する」というビジョンを掲げています。このビジョンの背景には医療従事者(特に医師)の世界が閉じられていると言われていて、弊社は彼ら同士の情報交換や相互協力が起きづらいことを課題として捉えています。そこでWebという開かれた空間を活用し、情報交換等を促すことで(弊社では集合知と呼んでいます)医師をサポートし、その先にいる患者を救うということがグループ全体の目標です。

## 裁量
私自身の話ですが、グループ全体のフロントエンド技術の底上げをしたいという希望が通り2018/10/1よりサーバーサイドエンジニアからフロントエンドエンジニアへの転身をしました(1年半の間、社内にフロントエンドエンジニアがいない状態が続いておりました)。

それに伴い、リードフロントエンドエンジニア採用もこのように任せていただいています。
会社として「裁量の仕組み化」はやってないと認識していますが、「言って行動すれば通る」状態ではあると思います(もし機会があれば、azu様の想像される「裁量の仕組み化」がどのようなことなのか教えていただけたら幸いです)。

## プライバシー
```
国内向けのプロダクトを運営しているため、GDPRに沿って個人情報取り扱いに対するルールを整備しているわけではありません。
```
上記ですが、完全に私が間違った認識をしておりました。例え国内向けプロダクトでも、EU居住者が使用していれば適用可能性があるということを認識していませんでした。GDPRの遵守については上述で相違ありません。(2018/11/14追記)

「Privacy by Design」については、私が今日この言葉を知ったということもあり、ここでの発言は控えさせていただきます(即答できず申し訳ありません)。

## リモートワーク
創業当時(2004年)から2017年までリモートワークを会社の制度として取り入れていませでした(しかし制度にないだけで、調整して特定の日をリモート勤務で働いている人もいますので禁止となっていたわけではありません)。
2018年より週1回のリモートワークを制度として取り入れられました。

## 情報の公開
上場企業ですので、売上や利益といった数値的なものはコーポレートサイトに載せております。
他の情報(エンジニアのアウトプット・取り組み・雰囲気)はテックブログを見ていただけたらと思います。

## 想定年収
800万円~1000万円

**Comment by pipopotamasu** [comment]
余談ですが、以前twitterで共有していただいたPubmed論文の日本語共有サービスを作ったものです。
https://twitter.com/azu_re/status/1025198744713609217

**Comment by azu** [comment]
@pipopotamasu ご連絡ありがとうございます。

> 医療系、医師向けのポータルサイトをメインに運営している会社です。

以前ヘルスケア関係の会社に関わりがありましたので存じ上げています。
(グループ会社だったのは知らなかったですが)

領域は異なりますがなんとなく[弁護士ドットコム](https://corporate.bengo4.com/)さんと似たイメージを持っていました。

> 現在社内にフロントエンドエンジニアが1名しか居らず
> 正社員として4名デザイナーが在籍しています

少し珍しいバランスですね。
今まではフロント専業の方がいない形で、サーバサイドの方がフロントもやっていたイメージでしょうか?

> 裁量の仕組み化

これは自分も明確なイメージは持っていないのですが、社員自身が「自分たちには裁量がない」と思い込んでいると、実際に権限があっても裁量を行使しなくなるかな(技術的なところだと新しい有料のサービスを使いたいなど)という印象があります。
そのため、裁量を持っているということを明らかにすることで心理的な安全性を確保するようなことを「仕組み化」と表現していました。
(または手続き的なものが複雑化して、簡単に行使できなくなる問題を抱えないようにするための仕組みなど)

**Comment by pipopotamasu** [comment]
azu様

ご返信ありがとうございます、メドピア株式会社 村上大和です。

> グループ会社だったのは知らなかったですが
2016年に企業買収等でメドピア含め計4社の企業グループとなりました。

> なんとなく領域は異なりますが弁護士ドットコム <https://corporate.bengo4.com/>さんと似たイメージを持っていました。
弊社メドピアが運営します、イシコメ <https://ishicome.medpeer.jp/>
というサービスが弁護士ドットコム様に近いビジネスモデルを展開しています。
もちろんイシコメにも注力していますが、メドピア株式会社として事業のメインはこちらではなく、医師向けのポータルサイト「MedPeer
<https://medpeer.jp/>」になります(医師向けのサイトのため、中を見ていただくことができず申し訳ありません)。

> 今まではフロント専業の方がいない形で、サーバサイドの方がフロントもやっていたイメージでしょうか?
現状ではデザイナーとサーバーサイドエンジニアがフロントエンドの実装を行なっております。
分担としてはデザイナーがメインでHTML,
CSSのマークアップ、サーバーサイドエンジニアがJavaScriptの実装及び小規模のHTML,CSSの改修という風に進めております。

> 裁量を持っているということを明らかにすることで心理的な安全性を確保するようなことを「仕組み化」と表現していました
そういった意味で言うと、週1回行われているエンジニア定例会議でツールや仕組み、制度の導入が話し合われることが多いです。
定例会議ではKPT <https://seleck.cc/kpt>を行なっており、Problemで出た解決策やTryの案としてツール・仕組み・制度の導入が決まることが多々あります。

esaの導入や、RubyのJob管理ライブラリの有料版導入、週1回のリモートワーク制度、エンジニアスキル向上制度(年間12万円まで、書籍・AWS等のクラウドサービス・IDE・資格費用等を会社負担で利用できる)などが
導入されました。
上記以外ですと、非エンジニアが2泊3日で平日に行われるエンジニア合宿に参加し、プログラミングに挑戦するといった自由度もあります(もちろん業務をきちんとこなした上での自由ですが...)。
「*この制度があるからこれほどの裁量がある*」という風に断言はできないですが、上記のような例で雰囲気を感じ取っていただけたら幸いです。

以上、またご質問などがありましたら気軽にご連絡いただけたらと思います。
弊社に限らず、azu様が満足行く転職活動が行えることを心より願っております(もちろん弊社に興味を持っていただけたら幸いです)。

 村上

2018年11月14日(水) 18:07 azu <notifications@github.com>:

**Comment by pipopotamasu** [comment]
@azu 
ご返信ありがとうございます。

> グループ会社だったのは知らなかったですが

2016年に企業買収等でメドピア含め計4社の企業グループとなりました。

> なんとなく領域は異なりますが弁護士ドットコムさんと似たイメージを持っていました。

弊社メドピアが運営します、[イシコメ](https://ishicome.medpeer.jp/)というサービスが弁護士ドットコム様に近いビジネスモデルを展開しています。もちろんイシコメにも注力していますが、メドピア株式会社として事業のメインはこちらではなく、医師向けのポータルサイト「[MedPeer](https://medpeer.jp/)」になります(医師向けのサイトのため、中を見ていただくことができず申し訳ありません)。

> 今まではフロント専業の方がいない形で、サーバサイドの方がフロントもやっていたイメージでしょうか?

現状ではデザイナーとサーバーサイドエンジニアがフロントエンドの実装を行なっております。
分担としてはデザイナーがメインでHTML, CSSのマークアップ、サーバーサイドエンジニアがJavaScriptの実装及び小規模のHTML,CSSの改修という風に進めております。

> 裁量を持っているということを明らかにすることで心理的な安全性を確保するようなことを「仕組み化」と表現していました

そういった意味で言うと、週1回行われているエンジニア定例会議でツールや仕組み、制度の導入が話し合われることが多いです。

定例会議ではKPTを行なっており、Problemで出た解決策やTryの案としてツール・仕組み・制度の導入が決まることが多々あります。

esaの導入や、RubyのJob管理ライブラリの有料版導入、週1回のリモートワーク制度、エンジニアスキル向上制度(年間12万円まで、書籍・AWS等のクラウドサービス・IDE・資格費用等を会社負担で利用できる)などが
導入されました。

上記以外ですと、非エンジニアが2泊3日で平日に行われるエンジニア合宿に参加し、プログラミングに挑戦するといった自由度もあります(もちろん業務をきちんとこなした上での自由ですが...)。
「この制度があるからこれほどの裁量がある」という風に断言はできないですが、上記のような例で雰囲気を感じ取っていただけたら幸いです。



以上、またご質問などがありましたら気軽にご連絡いただけたらと思います。
弊社に限らず、azu様が満足行く転職活動が行えることを心より願っております(もちろん弊社に興味を持っていただけたら幸いです)。

**Comment by azu** [comment]
@pipopotamasu 詳細な回答ありがとうございます。
あらためて[メドピア開発者ブログ](https://tech.medpeer.co.jp/)を読んだり、いろいろ調べていました。

[レポート](https://sharedresearch.jp/ja/6095)などを読んでいると競合他社さんに比べてドクタープラットフォーム(B2B)やヘルスケア(B2C)どちらもあったり、[薬剤師プラットフォームへの横展開](https://prtimes.jp/main/html/rd/p/000000156.000010134.html)などプラットフォームとしての幅の広さがメドピアさんの強みなんだと思います。

一方で、少し気になったのが医師といったように（すでに見えている）市場に限定されやすい傾向があるのではないかと思ったところです。（これは医師目線のサービスだったり、[理念](https://medpeer.co.jp/recruit/company/statement.html)からも見てまっとうだと思います)

たとえば、メドピアの薬剤評価掲示板のことを「[医師版食べログ](https://shikiho.jp/tk/news/articles/0/47349/1)」という話があったりますが、ターゲットが決まっているので「〇〇版のXXX」という話になりやすいようにも感じました。
どちらかという自分はXXXの方を作ることに関わりたいという気持ちがあります。
（これはその概念が十分一般化されたため医師版というかたちになったりするわけで、それは正しい判断だと思います）

また、[有価証券報告書の【事業等のリスク】の技術革新について](http://resource.ufocatch.com/pdf/edinet/ED2017121900164)でも書かれていましたが、今のインターネットはまだまだ発展途上でいろいろな新しいものがでてくるタイミングだと思います。
医療やヘルスケアにも興味はあるのですが、自分は新しいものに対してより挑戦しやすいものへの興味が強いと感じました。（そこまでスタートアップ志向ではないですが、新しいものが出てきたときにすぐ反応できる距離にいたい）

医療などの分野そのものの性質だと思うのですが、医療分野などではリスクが命に直結してしまうゆえ様々な規制などもあり、簡単に試すといったような挑戦が難しい環境であるかなと思います。（これは実証実験から先に進むのが難しいといった経験的な感想が含まれています）もちろん[キュア・アップ](https://cureapp.co.jp/)さんがやっている治療アプリのような新しい取り組みもありますが、その開発プロセスはやはり慎重になるのが当然だと思います。

- [【第4回】米国で増加する「治療アプリ」](https://healthtechplus.medpeer.co.jp/trend/1269)

そのため、「集合知で医療を再開発する」は挑戦的という意味では同じではありますが、今回は自分の心境との相性からミスマッチしてしまう部分があるかなと感じました。

申し訳ありませんがクローズさせていただきます。いろいろと詳しい説明ありがとうございました！

**Comment by pipopotamasu** [comment]
@azu 
ご検討ありがとうございました。

> ターゲットが決まっているので「〇〇版のXXX」という話になりやすいようにも感じました

かなり確信をついている考察だと思います。他社で成功しているビジネスモデルを医師の世界に持ってくるというアイデアは社内で多いと感じています(あくまで私の感想です)。

これほど入念に調べてられるとは正直かなり驚きました。
是非azuさんとベストマッチする企業様に出会えることを願っております。

次回JSer.infoのイベントを開催されるときは、私もお邪魔させていただきたく思っておりますので宜しくお願い致します！

**Comment by azu** [comment]
> 次回JSer.infoのイベントを開催されるとき

はい、よろしくお願いします！
