### ISSUE TITLE
サイボウズ株式会社

### ISSUE THREAD

**Issue by koba04** [azu/open-job-letter#6]
サイボウズ株式会社 フロントエンドエキスパートチームのkoba04です。

## 連絡した背景

サイボウズのフロントエンドの基盤作りを一緒に行って頂きたいと考え、ご連絡させて頂きました。
サイボウズでは、各プロダクトの開発を行うエンジニアはサーバーサイドとフロントエンドのどちらも担当します。
これは、サーバーサイドからフロントエンドを含めて最適化した設計ができることや、サーバーサイドからフロントエンドまで一気通貫したプロダクトに対する理解が深まるといったメリットがあります。
また、各エンジニアがサーバーサイドエンジニアとフロントエンドエンジニアのどちらも担当できるため、柔軟なチーム構成を可能にします。

その一方、フロントエンドにおけるさらなる探求については各メンバーの自発的な活動によって行われていました。
JSer.infoを使ったフロントエンドランチもその一貫です。

加えてサイボウズの場合は、kintoneをはじめカスタマイズやプラグインといった形により、kintoneの上でHTML/CSS/JSを使って開発するプラットフォームとしての役割もあります。
したがって、プラットフォームとして開発者に対するライブラリやツールの提供といった役割もあります。

* Developer Networkのサイト
    * https://developer.cybozu.io/hc/ja
* kintoneのGitHubリポジトリ
    * https://github.com/kintone

これらの活動については、下記の資料にて紹介しています。

* 100人100通りのフロントエンド
    * https://speakerdeck.com/koba04/100ren-100tong-rifalsehurontoendo

2017年10月にフロントエンドを専門的に行うフロントエンドエキスパートチームが誕生し、フロントエンドに対する探求をプロダクトチームと一緒に行うことや、勉強会などの開催による情報共有や教育、研究開発を行うための役割が正式に誕生しました。

これらの活動は、azuさんの下記の思いに近いのではないかと思い、今回連絡させて頂きました。

> また、自分自身が特定のドメインに詳しくなり単一障害点となることよりも、 特定のドメインに取り組んでいる人を支援して課題を解決する手伝いをしたいという思いがあります。

フロントエンドエキスパートチームについても、まだまだ試行錯誤している段階です。
これまでにazuさんが行われていたような会社全体のフロントエンドを改善する活動の経験をもとに、是非一緒にサイボウズ全体のフロントエンドを改善していきたいと思っています。

## 事業、市場、規模

サイボウズは「チームワークあふれる社会を創る」という理念に沿って、チームワークを支えるソフトウェアを開発している会社です。

https://cybozu.co.jp/

現在は、

* [kintone](https://kintone.cybozu.co.jp/jp/) ... ビジネスアプリ作成クラウド
* [Garoon](https://garoon.cybozu.co.jp/) ... 中規模、大規模向けグループウェア
* [サイボウズ Office 10](https://products.cybozu.co.jp/office/) ... 中小規模向けグループウェア
* [メールワイズ](https://mailwise.cybozu.co.jp/) ... メール管理サービス
* [サイボウズLive](https://live.cybozu.co.jp/) ... 無料チャット・無料グループウェア (2019年4月終了予定)

を提供しています。
これ以外にも、上記のサービスを提供するのに必要なシステムが存在します。

当初はパッケージ製品として提供していましたが、2011年からはクラウドサービス「cybozu.com」の提供を開始しており、
現在ではクラウドサービスによる売上がパッケージ製品の売上を上回っています。
規模感としては、契約社数が27,000社以上、契約ユーザーライセンスは140万人以上となります。

社員数は約800名で、国内以外にも中国、ベトナム、米国に拠点があります。
売上も2016年が約80億円、2017年が約95億円、2018年は第3四半期の時点で約82億円(前年同期比20%増)と、
パッケージ製品の安定した売上とクラウド製品の伸びにより、成長を続けています。

国内では、kintoneの利用企業数が10,000社突破、サイボウズOfficeは60,000社突破、Garoonは4,800社突破など確固たる地位を確立しています。
海外では、中国、東南アジア、米国においてサービスを展開しており、米国ではkintoneはリブランディングした形でサービスを展開しています。

https://www.kintone.com/

現在は米国市場をさらに拡大すべく、開発基盤をcybozu.comからは切り離してAWS上で提供するための開発を行なっております。

* kintoneがAWSで目指すDevOpsQAな開発
    * https://www.slideshare.net/teppeis/kintone-awsdvopsqa-111906067

## デザイン

サイボウズにはデザイングループがあり、プロダクトチームの一員として活動しています。
デザイングループについては、下記を参照ください。

* https://cybozu.co.jp/company/job/recruitment/designgroup/

社内にユーザーテストのための環境があるため、頻繁にユーザーテストを行いながら改善を続けています。
また、サイボウズの社員はサイボウズ製品を使って業務を行なっているため、すぐにフィードバックを受けることが可能です。

また最近では、モバイルページのリニューアルに取り組んでおり、
エンジニアとデザイナーが一緒にモブプログラミングを行いながらデザインを作りあげています。

* kintoneの新モバイル画面について
    * https://www.kinsuki.com/entry/cybozudays2018?utm_source=feed#%E4%B8%80%E7%B7%92%E3%81%AB%E6%96%B0%E3%83%A2%E3%83%90%E3%82%A4%E3%83%AB%E7%94%BB%E9%9D%A2%E3%82%92%E4%BD%9C%E3%82%8D%E3%81%86

デザインツールやコンポーネント志向、デザインシステムについては、
今まさに社内で探求が行われている段階で、勉強会なども開催されており、サイボウズでのあるべき姿を探求しているところです。

その他としては、チームにいる誰もがアクセスできる製品を目指した、アクセシビリティに対する取り組みも各チームで行われています。

* アクセシビリティへの取り組み
    * https://cybozu.co.jp/efforts/accessibility/
* 各チームのアクセシビリティへの取り組み
    * https://cybozu.connpass.com/event/106185/presentation/

## チーム

サイボウズでは、製品に対して、開発のプロダクトマネージャーとビジネス側のプロダクトマネージャーがいて、
開発PMは製品に対しての方向性や戦略を決定し、ビジネス側のPMは販売戦略を決定します。

* 「世の中に価値を届けよう！」サイボウズのプロダクトマネジメントについて
    * https://blog.cybozu.io/entry/product-manager

また、開発では、エンジニアやデザイナー以外にも、QAやSRE、TC(Technical Communication)、PSIRTなど多くのメンバーが関わっています。
現在では多くのチームがスクラムを採用しています。

* チームワークあふれる働き方を目指して -サイボウズが歩んだスクラム導入の道-
    * https://www.slideshare.net/ama-ch/ss-86003462

エンジニアやデザイナー、QAなどクロスファンクショナルなプロダクトチームとは別に、専門性を持ってプロダクトチームを支援するチームが存在します。
フロントエンドエキスパートチームもその1つです。
その1つである生産性向上チームと支援チームの役割については下記のスライドを参照ください。

* 組織横断でエンジニアを支援する生産性向上チームの役割
    * https://www.slideshare.net/miyajan/ss-83175725

また、サイボウズ・ラボという組織もあり、より長期の視点で研究開発を行ったり、OSS開発、標準化活動、教育活動などに注力することも可能です。

* サイボウズ・ラボ
    * http://labs.cybozu.co.jp/

## テクノロジー

kintoneはクラウド型のデータベースを提供するサービスで、業務アプリケーションを簡単に作成できます。
開発の知識がなくてもドラッグアンドドロップなどの直感的なUIで簡単に業務アプリケーションを作成できるため、業務を改善したいと思った時にこれまでは開発会社やエンジニアに頼むしかなかったことも、自分たちでkintoneのアプリケーションを作成することで実現できるようになります。

kintoneを使った業務改善のストーリーを発表するkintone hiveというイベントも行われています。

* kintone hive
    * https://kintone.cybozu.co.jp/jp/event/hive/
* 業務を変えるkintoneユーザー事例
    * http://ascii.jp/elem/000/001/435/1435280/
* 社長にはもうついていけませんー疲弊した老舗企業が「残業ゼロ」で最高益を更新するまで
    * https://cybozu.co.jp/sp/workstyle/workstyle11.html

kintoneを支えるテクノロジーとして、柔軟でスケーラブルな仮想データベースを実現するサーバーサイドアプリケーションやインフラの技術と、誰もが簡単にアプリケーションを作成出来るようにするためのフロントエンドの技術が重要な要素となります。

フロントエンドについては、大規模な開発に対応するためサイボウズでは静的型付けなどの技術に早くから取り組んできました。
また、前述した通り、kintoneはHTML/CSS/JSなどフロントエンドの技術を用いたプラグインやカスタマイズという形で拡張が可能です。
このエコシステムをさらに広げていくためのDX(Developer Experience)を提供するための開発や情報提供も行なっています。
モバイル上でカスタマイズのあるべき姿などは今後検討すべき課題の1つです。

また、これらを実現するための基礎として、CI/CDや自動テスト基盤による品質向上やリリースの高速化といった取り組みにも力を入れています。

取り組んでいる技術については、エンジニアブログで公開しているのでそちらもご参照ください。

* https://blog.cybozu.io/

## 透明性

開発のメンバーだけではなく、全ての社員がkintoneやGaroon上で仕事をしているので、全ての情報が集約されています。
エンジニアに限らず、全社員がオンラインコミュニケーションツールを使いこなしていることは、サイボウズの大きな特徴の1つです。
kintone上でいわゆる分報をつぶやいている社員も多く、そこをきっかけに部署や役職を横断して議論が起きることもよくあります。

また、社内の情報はできるだけオープンに公開されています。
例えば経営会議の議事録と資料が全社員に公開されているので、誰がどのような発言をしたのかということも知ることができます。

社外においても、社内の制度などはサイボウズ式などのメディアで積極的に公開されています。

https://cybozushiki.cybozu.co.jp/

また、最近はOSSポリシーを策定して外部に公開しました。
その際、頂いた意見に対しての見解も公開しています。

* サイボウズのオープンソースソフトウェアポリシーを紹介します
    * https://blog.cybozu.io/entry/oss-policy
* 業務利用しているOSSの休日個人開発は業務か？
    * https://blog.cybozu.io/entry/2018/09/13/113000

## 課題

パッケージ製品からクラウド製品に移行していく中で、開発のスタイルやインフラのあり方もクラウドにあった形に変えていくのが今の大きな課題です。
アーキテクチャ、開発・運用のプロセスや体制、CI/CDなどリリースフローなどを見直し、ユーザーに対してより高い価値をよりスピーディに提供していくことを目指しています。
kintone.comをAWS化する「Yakumo」プロジェクトや、インフラのアーキテクチャ刷新を行う「Neco」プロジェクトなどはそれを解決するための取り組みの一部です。
Necoの成果物はGitHub上で公開されています。

* Yakumo: kintnoe.comのAWS化プロジェクト
    * [kintoneがAWSで目指すDevOpsQAな開発](https://www.slideshare.net/teppeis/kintone-awsdvopsqa-111906067)
    * [Kubernetes+Amazon EKSで自社サーバからAWSへ　サイボウズの狙いは「人がやることを減らす」 - エンジニアHub｜若手Webエンジニアのキャリアを考える！](https://employment.en-japan.com/engineerhub/entry/2018/11/20/110000)
* Neco: アーキテクチャ刷新プロジェクト
    * [アーキテクチャ刷新プロジェクト「Neco」の紹介 - Cybozu Inside Out | サイボウズエンジニアのブログ](https://blog.cybozu.io/entry/2016/03/11/080000)
    * [インフラ刷新プロジェクト「Neco」が目指す最高のクラウドとは](https://www.slideshare.net/ShinyaUeoka/neco-119734740)
    * https://github.com/cybozu-go

またプロダクトが巨大になるにつれて、属人性が増えてしまう部分があるため、多くのチームでモブプログラミングなどを通じて知識の共有が行われています。

フロントエンドに関して言えば、素早い改善とリリースを可能にするためのリファクタリングが課題としてあります。
その一環としてビューとドメインをしっかり分離する取り組みが行われており、kintoneではReactやFluxが取り入れられています。
またコードの規模が大きいため、Lint系のツールの導入やリファクタリングの際にもcodemodを使ったアプローチが採用されています。
プロダクトが巨大になるとコアとなる部分に手を入れるのが難しくなるため、今後は如何にドメインを分割するかといったことも課題になってくると考えています。

kintoneが提供しているプラグインシステムにおいても、改善を進めていますがまだまだ不足している部分が多く、
npmフレンドリーな開発者に対しても、そうでない開発者に対しても更なるDXの向上が課題としてあります。
また、ブラウザ上で動作するサードパーティ製のプラグインをよりセキュアで互いの干渉がない形で提供する、という点も今後の課題です。
これはECMAScriptの言語仕様やセキュリティ関連のWeb APIの策定動向を見守りながら検討していきたいと思っています。

モバイルについては、以前はあまり注力していませんでしたが、現在はモバイルチームもできてフォーカスして開発に取り組んでいる分野です。
Webとネイティブの使い分け、カスタマイズの提供方法、パフォーマンス、PWA関連技術など、より良いモバイルUXを提供するために今後取り組んでいきます。

また、ヘルプなどの文章を作成するテクニカルコミュニケーショングループでは、文章の校正にtextlintを利用したりコンテンツの配信にNetlifyを利用することで、
校正の自動化やリリースの高速化に取り組んでいます。

## 裁量

具体的な仕組みと言われると難しいですが、サイボウズは「チームワークあふれる社会を創る」という理念のもとに集まっているチームであり、それを実現するために必要なことであれば実現できる環境です。

サイボウズでは、どのような働き方がしたいのかやどれくらい給与が欲しいのかなども含めて、自分がどうしたいのかを表現する必要があります。
このように何が希望がある場合は、それを表現することが当たり前な風土があります。

* 初公開！サイボウズの自由すぎる働き方はこんなやり方で管理されていた
    * https://cybozu.co.jp/sp/workstyle/workstyle22.html
* ここまで見せていいの？ーサイボウズの「給与評価」と「キャリアパス」の裏側を、人事が赤裸々に語る
    * https://cybozu.co.jp/sp/workstyle/workstyle24.html

kintoneにはピープルという個人のタイムラインのようなものがあり、ここで気軽に発言することで新しい動きのきっかけになることもあります。

また、サイボウズでは、説明責任と質問責任があります。
質問責任とある通り、何か疑問に思うことがあれば質問して議論を行う必要があります。
そのため、議論が発生することもありますが、職場は多様な人が集まっているという前提があるため異なる意見も受け入れられる風土があると思います。

* なぜサイボウズは働く「時間」と「場所」の制約をなくせたのか？（後編） －変革のカギは社員の自立－
    * https://cybozushiki.cybozu.co.jp/?p=8562

## プライバシー

GDPR対応については、現在は社外にアナウンスするため準備している状態であるため、ここでの回答は差し控えさせていただきます。

## リモートワーク

サイボウズでは、ツール、制度、風土の3点でアプローチしています。

* ツール
    * グループウェア
    * テレビ会議システム
    * 在宅勤務用PC
    * 外部アクセス
* 制度
    * 100人100通りの働き方
    * ウルトラワーク
* 風土
    * 多様性
    * 複数拠点をまたいだチーム

サイボウズでは、リモートワークは「特別」な状態ではないため、スムーズに行うことができると思います。
勉強会なども多くの場合は、他拠点だけでなく自宅から参加、登壇も珍しくありません。
これを実現するために、制度やツールの整備を積極的に行なっています。

* リモートワークで場所から解放されたのに、精神的に縛られた。けどやってよかった──パリ×新潟からリモートの本音を語ってみた
    * https://cybozushiki.cybozu.co.jp/articles/m001375.html
* 京都在住、時々大阪、アメリカ向けの基盤開発
    *  https://www.slideshare.net/RyoMitoma/ss-108863692

**Comment by azu** [comment]
ご連絡ありがとうございます。
サイボウズ社に関しては10年ぐらい前から知っていて、変化を見てきているのでなんとなくは知っていましたが、改めて全体的な情報ありがとうございます。

> パッケージ製品からクラウド製品に移行していく中で、開発のスタイルやインフラのあり方もクラウドにあった形に変えていくのが今の大きな課題です。
アーキテクチャ、開発・運用のプロセスや体制、CI/CDなどリリースフローなどを見直し、ユーザーに対してより高い価値をよりスピーディに提供していくことを目指しています。

外から見ていても、[リリース](https://kintone.cybozu.co.jp/jp/feature/whatsnew.html)の[サイクル](https://garoon.cybozu.co.jp/support/whatsnew/cloud/)に課題があるのかなと思っていたので、その辺の認識が一致していてよかったです。

> 近年のB2Bサービスはちゃんとデザインされており活発に開発されているものが増えたという印象があり
-- https://github.com/azu/open-job-letter#転職活動の目的

[求職記事の目的](https://github.com/azu/open-job-letter#%E8%BB%A2%E8%81%B7%E6%B4%BB%E5%8B%95%E3%81%AE%E7%9B%AE%E7%9A%84)のところでこのように書いていたのも、伝統的なパッケージ版とクラウド版(SaaS)のモデルの違いから、開発のサイクルが異なる部分が多少なりあるのかなと思っていたからでもあります。
またB2BであってもB2Cのように開発しないとスピード感がたりなくなったり、サービスの利用者もオンプレじゃなくてクラウドサービスを利用することに慣れてきているのもあって、そういうB2Bサービスが増えたのかなと思っています。

- e.g. [https://www.salesforce.com/jp/solutions/small-business-solutions/resources/SaaS-Startup-Founders-Guide/](https://www.salesforce.com/jp/solutions/small-business-solutions/resources/SaaS-Startup-Founders-Guide/)

書いていただいたリソースを見てみます。

**Comment by teppeis** [comment]
@azu 

> B2BであってもB2Cのように開発しないとスピード感がたりなくなったり、サービスの利用者もオンプレじゃなくてクラウドサービスを利用することに慣れてきている

まさにその通りです。
B2Bには、B2Cに比べると長期的視点で良いプロダクトを作り込んでいけるビジネス的な性質があると思いますが、だからと言ってスピードが遅くて良いわけではないので、そこを解決していきたいと思って取り組んでいます。

**Comment by azu** [comment]
サイボウズ社についての[書籍](https://www.amazon.co.jp/dp/B019DFSTIC/)や最近の[変化](https://twitter.com/y_okady/status/1071569138659733504)なども見ていて、組織的に魅力がある会社だと思いました。
最近[ティール組織](https://www.amazon.co.jp/dp/B078YJV9ZW/)を読んでいたので、こういう組織があるのは珍しいと思っていたのもあります。
(これはリモートワークへの興味で書いていたのと似たような理由で、そういう変化をおこなっている組織に興味があった)

ただ、自分はグループウェアを作ることへの興味があまり高くありません。
また、今回の募集では、HRなど組織に関するサービスを提供する企業からの応募がもっとも多かったです。(詳細なレポートは後日公開します)
そのため、組織/チームを改善/ワークするプロダクトに挑戦したいかは色々考えていましたが、興味自体はあるが今挑戦したいことではないと思った経緯もあります。
(どんな会社でも組織的な課題はあると思うのでそれに向き合う必要はあると思っていますが、それに関連することを事業として取り組みたいかと考えたときに、そうではないなと思いました)

色々な情報頂き申し訳ありませんが、クローズさせていただきます。

**Comment by koba04** [comment]
ご検討頂きありがとうございました！
今後、「チームワーク溢れる社会を創る」という活動に興味が高まった際には、フルタイム以外でも様々な形で一緒に取り組むことが可能ですので、お気軽にお声がけ頂けると幸いです。

**Comment by teppeis** [comment]
@azu ご検討ありがとうございました！今後ともよろしくお願いします。
