### ISSUE TITLE
Quipper Limited

### ISSUE THREAD

**Issue by kyanny** [azu/open-job-letter#7]
初めまして。 Quipper で VP of Engineering をやっている長永（@kyanny）と申します。

ちゃんとした文章の形に清書してから投稿すべきだとは重々承知しているのですが、締切まで残り時間が少ない中で、体裁が整っていることよりは伝えたい内容が列挙されていることのほうが重要だと考えるので、以下箇条書きで失礼します。

- open job letter を読んで興味を持ちました
- 活躍してもらえることがいろいろあるのではないかと思って連絡しました

# 会社の紹介

- Quipper はオンライン教育サービスを提供している会社です
- 2015年にリクルートグループ入りし、日本・インドネシア・フィリピン・メキシコにオフィスがある
- 日本ではスタディサプリ、インドネシア・フィリピン・メキシコでは Quipper Video / Quipper School といったブランドでサービスを展開している
- Disbributors of Wisdom というビジョン・Bring the best education to all corners of the world（世界の果てまで最高の学びを届けよう）というミッションを掲げている
- メンバー数は日本オフィスで150名以上、グローバルでは500名以上（スタートアップ→リクルートグループ入り後、拡大中）

# 事業の紹介

- スタディサプリ・Quipperともに BtoC と BtoBtoC の両方をやっている
- BtoC: スタディサプリ（月額980円で動画見放題サービス、月額9800円で専任コーチが伴走する合格特訓コース）
- BtoBtoC: スタディサプリ for Teachersとセットで日本全国の学校に導入いただいている（主に高校、一部の自治体で小中学校も）
- Quipperも同様（Quipper Video が BtoC、Quipper School が BtoBtoC）
- 異なる背景事情を持つビジネスからの要求を共通したシステム・プラットフォームで担っているため、プロダクト開発において難しさもあり、挑戦しがいがある部分でもある
- 脱スタートアップという事業フェーズ https://speakerdeck.com/takuboxx/educational-business-and-our-business-phases?slide=13

# プロダクトとテクノロジーの紹介

- ユーザー向けに提供しているのは大きく二種類。生徒用と先生用
- 生徒用: Learn と呼んでいる。生徒が動画をみたり演習問題を解いたりするアプリ。 Web / iOS / Android がある。 Web 版が最も古く、 Marionette.js を使っている。 React + Redux / TypeScript で作り直している最中
- 先生用: Link と呼んでいる。先生が宿題を配信したり他にもいろいろするアプリ。 Web 版のみ。これも Marionette.js だったが React + Redux で作り直した
- 昔から Web アプリの開発のウェイトが大きかった。理由:
  - スタートアップ時代はスマホ普及率の低い海外が主戦場だったため Web アプリから作るのが妥当だった
  - Web エンジニア（バックエンド）の人数が多かったので Web フロントエンドの開発のほうが native アプリよりパワーをかけやすかった
- 今後も Web アプリの開発には引き続き力を入れていく（native も。両方やる）
- 主力の2プロダクト以外にも、学習コンテンツを入稿するCMSや各国の決済システムとつなぎ込みをするアプリケーション、いわゆる「管理画面」アプリケーションなどなど、いろいろある
- サーバサイドは Ruby / Rails で書いている
- インフラ基盤部分は Heroku -> Deis ときて最近 Kubernetes へ移行した https://quipper.hatenablog.com/search?q=kubernetes 

# 課題

- いろいろある
- 組織、サービス、プロダクト、システム、 etc.
- テクノロジー・エンジニアリングで解決・改善できる余地はたくさんあると思っている
  - 例: 我々のプラットフォームにはユーザーの膨大な行動ログ（動画視聴、演習問題回答、など）がある。これを活用すれば、ユーザーの学習進捗に応じて次に学習すべき適切なコンテンツを推薦するなどの仕組みを提供でき、効率の良い学習が実現できるはずだが、まだ取り組み半ばである
  - 例: BtoC サービス向けに提供しているアプリ（フロントエンド）で、 A/B テストで機能や施策の効果測定をしてプロダクトを磨いていきたいが、学習効果に優劣が生じるような安易な A/B テストを実施できない（劣る機能をユーザーに提供して良いのか？という倫理的な点も考慮が必要）
  - 例: BtoBtoC サービスにおいて、年度という単位で物事が進むビジネスで、学校での利用のされ方も学校の年間スケジュールなどにも深く関わってくるため、UIや機能の大幅な変更を年度内に行うことが難しい（学校の先生や、営業担当者などの立場では、プロダクト・サービスの大きな変更は年度切り替わりのタイミングに寄せて欲しい。これはプロダクト側の理想とするリリースサイクルとは一致しないことも多々ある）
  - 例: （急に細かい話になるが） UI の細かい部分のチューニングをしたいとデザイナーもエンジニアもプロダクトマネージャーも皆思っているが、事業としてやる上での優先順位付け・プロダクト側のリソースなどの関係で思うようにやれていない。基本的な部分でも十分に手が回っていない。アクセシビリティ・パフォーマンス・UXデザインなど、様々な領域での改善の余地が多く残っている。
- これまでオープンな場で他社のオファーへの回答などを拝見し、 azu さんは「自分がその企業でその仕事をする理由」に強いこだわりを持っていると感じている
- 言い換えると、「自分に期待されるミッションは何か」に対する強いこだわりがある、と推察する
- 我々も「azu さんに期待するミッション」を明らかにした上でオファーしたいと思っているし、課題はたくさんあるので期待したいこともたくさんあるが、「どんな課題があるか」「その課題をどのように解決していくか」のすり合わせは、後述する理由により、直接話さないと難しいと思う
  - お互いにテキストで伝わることには限度がある。直接話すことで得られる情報量は圧倒的に多い
  - Quipper は Slack/GitHub を中心に海外オフィスのメンバーとも連携しながら開発プロセスを進めていて、テキストベースのコミュニケーションの効率の良さは十分に実感しているが、同時にテキストベースのコミュニケーションの難しさも十分に実感している
  - 機能開発の仕様の認識合わせなど、「答えがある問題」ですらコミュニケーションがすれ違うことは多々あるので、「課題と解決アプローチの認識すり合わせ」という高度に抽象的なコミュニケーションをテキストベースで行うのは難易度が高すぎる（不可能ではないだろうが、効率が悪い）
  - 要するに「コミュニケーションが大事だと考えているので、コミュニケーションしやすい手法でやりたい」
- もし Quipper に興味を持っていただけるならば、ぜひ一度お話したい。その上で azu さんと一緒にやっていく可能性があるかどうか、話し合いたい
- オフラインの場で直接会って話せると、より多い情報量でコミュニケーションできるので、こちらとしてはありがたいが、オフラインの場で直接会うのはコストが高く、 azu さんにとって負担になるとも思うので、 Skype などビデオ会議システムでオンラインで話すのでも構わない
- オフラインで会っても良いという場合、場所はどこでも構わない（azu さんにとって便利で快適であることが最優先と考えるので、弊社オフィスへ来てください、とは言いません。来てもらえたら我々は便利だが）。指定してもらえればそこへ行きます（東京周辺だとうれしい）

# その他のポイントについて

- 裁量/透明性、チーム/人: 私がテキストで綺麗事を書いたところで実態とずれていたら無意味なので、チームのメンバーと話して確かめてほしい
  - 裁量/透明性: 仕組み化で解決しきれているとは言えないが、問題を感じたらオープンに意見を出して Slack/GitHub で議論を重ねつつ解決していくスタイル
  - チーム/人: 事業やプロダクトに対する関心・当事者意識が高く、主体的に行動するのを好む人が多い。逆に、自由な言動が制限されたり、不明瞭・理不尽な理由で何かをやらなければいけない、ということには強く反発する人が多い。
  - 過去に大量に採用→大量に離職、という苦い経験があり、反省を踏まえて「カルチャーフィット」を最重視するようにした。仕事に対するスタンス・考え方などの部分で「チームに合う」と思える人だけ採用するようにしている
  - プロダクトチームの雰囲気は https://quipper.hatenablog.com/ などでも
- プライバシー: 当然尊重すべきものだと思っている
- リモートワーク: 会社のスタンスは「出社を推奨（リモートワークを積極的に推奨はしない）」で、制度化してないぶん柔軟な運用でカバーしている。実態としては、リモートワーク多い人は週の半分以上はリモート。会議の調整など、自分の責任でやれるなら問題なし、としている（私個人としてはリモートワーク苦手なので積極的に出社したい派だが、世の中の流れ的にはリモートワーク含めて時間・場所から自由に働くという世界になっていくものと思っていて、会社としても適応していく必要があると考えている）
- 待遇: 正社員としてフルタイムで働いてもらうのが良いと思うが、お互いにとってベストな関わり方をしたい。 Mission Grade という人事評価制度を採用しており、与えるミッションに応じてグレードが定まり、グレードと給与テーブルが連動する。したがって「おまかせするミッション」がクリアにならないことには年収は決まらないので、「○万円以上保証」など現時点で約束はできない（が、できるだけ難易度の高いミッションをお任せできるならしたいと思っているので、納得いただける条件を提示できるのではと思う）
- いろいろ抜け漏れあると思うので、「この点について詳しく知りたい」というのがあればコメントください。回答できることは回答します（回答できないことはできるだけ理由を添えて「回答できない」と回答します）
- 「この点について、こういう立場・役割の人に聞きたい」というのがあれば、機会を作るので（テキストベースでも、口頭でも）それもコメントください

**Comment by azu** [comment]
ご連絡ありがとうございます。
Quipper社については[Quipper採用面接ガイド](https://quipper.hatenablog.com/entry/2018/09/01/interview-guide)や[Go global](https://speakerdeck.com/kechol/coding-test-for-web-dev-candidates-at-quipper)で聞いたお話などが印象に残ってます。

色々調べて考えてみた結果、今の自分には教育分野へのモチベーションがあまり高くないと思ったため、クローズさせていただきます。

以下箇条書きで失礼します。

- 教育については元々興味はあったので、色々な形で教育を届けること価値は感じている
    - ただし、初心者はどう学ぶかというところに興味がある印象
    - 教えると学ぶは表裏一体なので区別できないが、どちらかというと学び方に興味をもっている
- [atama plus](https://www.atama.plus/)の方から[話](https://twitter.com/ganzology/status/1066912558597062656)を頂いたときに、[Educational technology](https://en.wikipedia.org/wiki/Educational_technology)の事業について色々調べていた
- 調べてみて、自身の教育系の事業への関心はそこまで高くないことがわかった
    - 教育系の中で学生/学校向けの事業は既存のものの一部をデジタル化してるものが多い印象
        - [Edtechカオスマップ – Tomoki Fujii – Medium](https://medium.com/@tomokifujii/edtech-industry-map-210d73f8a7cf)
    - また既存のもの(例えば年度や受験)といったサイクルが長いものに合わせて開発する必要がある特殊性を感じた
        - 学校や受験などは特にこのサイクルに合わせて開発しないといけない
        - もちろんそうする必要がないものも多いと思いますが、メインはそこにある事業が多いのかなと思った
    - > "例: BtoBtoC サービスにおいて、年度という単位で物事が進むビジネス"
    - この例も長いライフサイクルの一例だと思った
    - このライフサイクルの問題を解決する(短期的に変更できるようにする)のは、契約などのビジネス的な面や(顧客が)変更を受け入れることでより良くなるという予測ができるような信頼性を得ることなどが起点となりそうだと思ってる(それを実装するのはテクノロジーだが、テクノロジーだけで置き換えるのは難しい問題だと思っている)
    - ⇒ この辺を解決するには必然的に長期的なサイクルが必要になってくると考えたときに、自身がこれを解決することに関わりたいと思えるほど関心は高くなかった

> azu さんは「自分がその企業でその仕事をする理由」に強いこだわりを持っていると感じている

- YES
- これは今回の求職記事における一種のフィルタ
- 他の人がどうやればいいのか困っている問題が自分のところへ来ることが多かった
- 一方で、自身の目標は自分以外でもその問題を解決できるようにすること(再現性を意識する)
- 自分自身がその企業で仕事をする理由をなくしていくようなイメージで動いている
- そのため長期的(5, 10年+)に同じところにいるイメージをあまりもっていない
    - 大きな課題に対して挑む場合には、それに対するモチベーションをしっかり持っていないといけないと考えている
    - 教育分野に関して、そのモチベーションが自分には足りないなと思った
- どういう課題をもっているか、どういう課題がでてきそうか(未知のものを含め)は、その企業で働くことによって自分自身が停滞しないかを判別する要素
